"use client";
import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import React, { useState } from "react";
import Link from "next/link";
import { CheckCircle2, Download, ArrowLeft, Lock, Sparkles, CreditCard, } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import { Card } from "@/components/ui/card";
import { initialProducts } from "@/lib/supabase/mock-db";
export default function StandaloneCheckoutPage({ params, }) {
    const [completed, setCompleted] = useState(false);
    const [paymentProvider, setPaymentProvider] = useState("stripe");
    // Lookup product or course
    const item = initialProducts[0];
    return (_jsxs("div", { className: "min-h-screen bg-zinc-950 text-zinc-100 flex flex-col justify-center py-12 px-4 sm:px-6 lg:px-8 grid-bg relative overflow-hidden", children: [_jsx("div", { className: "absolute top-1/3 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[600px] h-[350px] bg-indigo-500/15 blur-[140px] rounded-full pointer-events-none" }), _jsxs("div", { className: "max-w-xl mx-auto w-full relative z-10 space-y-6", children: [_jsxs(Link, { href: "/public/rajnish", className: "inline-flex items-center gap-2 text-xs text-zinc-400 hover:text-white transition-colors", children: [_jsx(ArrowLeft, { className: "h-4 w-4" }), "Back to Store"] }), _jsx(Card, { className: "glass-panel border-white/10 p-6 md:p-8 rounded-3xl shadow-2xl space-y-6", children: !completed ? (_jsxs(_Fragment, { children: [_jsxs("div", { className: "flex items-center justify-between border-b border-white/5 pb-4", children: [_jsxs("div", { className: "flex items-center gap-2", children: [_jsx(Lock, { className: "h-4 w-4 text-emerald-400" }), _jsx("span", { className: "text-xs font-bold text-white uppercase tracking-wider", children: "Outsyra 256-Bit Encrypted Checkout" })] }), _jsx(Badge, { variant: "success", className: "text-[10px]", children: "Instant Access" })] }), _jsxs("div", { className: "flex gap-4 items-center p-4 rounded-2xl bg-zinc-900/60 border border-white/5", children: [_jsx("img", { src: item.cover_image, alt: item.name, className: "h-16 w-16 rounded-xl object-cover border border-white/10" }), _jsxs("div", { className: "flex-1 min-w-0", children: [_jsx("h3", { className: "font-bold text-white text-sm truncate", children: item.name }), _jsx("p", { className: "text-xs text-zinc-400", children: item.file_name }), _jsxs("p", { className: "text-sm font-bold text-emerald-400 mt-1", children: ["$", item.price.toFixed(2), " USD"] })] })] }), _jsxs("div", { className: "space-y-2", children: [_jsx("label", { className: "block text-xs font-medium text-zinc-300", children: "Choose Payment Method" }), _jsxs("div", { className: "grid grid-cols-2 gap-3", children: [_jsxs("button", { type: "button", onClick: () => setPaymentProvider("stripe"), className: `p-3 rounded-2xl border text-xs flex items-center justify-center gap-2 transition-all ${paymentProvider === "stripe"
                                                        ? "bg-indigo-600/20 border-indigo-500 text-white font-bold"
                                                        : "bg-zinc-900/40 border-white/5 text-zinc-400"}`, children: [_jsx(CreditCard, { className: "h-4 w-4 text-indigo-400" }), "Cards / Apple Pay"] }), _jsxs("button", { type: "button", onClick: () => setPaymentProvider("razorpay"), className: `p-3 rounded-2xl border text-xs flex items-center justify-center gap-2 transition-all ${paymentProvider === "razorpay"
                                                        ? "bg-indigo-600/20 border-indigo-500 text-white font-bold"
                                                        : "bg-zinc-900/40 border-white/5 text-zinc-400"}`, children: [_jsx(Sparkles, { className: "h-4 w-4 text-pink-400" }), "Razorpay / UPI"] })] })] }), _jsxs("div", { className: "space-y-3", children: [_jsxs("div", { children: [_jsx("label", { className: "block text-xs font-medium text-zinc-300 mb-1", children: "Full Name" }), _jsx(Input, { defaultValue: "Sophia Martinez", className: "text-xs" })] }), _jsxs("div", { children: [_jsx("label", { className: "block text-xs font-medium text-zinc-300 mb-1", children: "Email Address" }), _jsx(Input, { type: "email", defaultValue: "sophia.m@gmail.com", className: "text-xs" })] })] }), _jsxs(Button, { variant: "gradient", className: "w-full h-12 text-sm font-bold shadow-lg", onClick: () => setCompleted(true), children: ["Pay $", item.price.toFixed(2), " USD Now"] })] })) : (_jsxs("div", { className: "text-center py-8 space-y-4", children: [_jsx("div", { className: "h-14 w-14 rounded-full bg-emerald-500/20 text-emerald-400 flex items-center justify-center mx-auto", children: _jsx(CheckCircle2, { className: "h-8 w-8" }) }), _jsx("h2", { className: "text-2xl font-extrabold text-white", children: "Order Completed! \uD83C\uDF89" }), _jsx("p", { className: "text-xs text-zinc-300 max-w-sm mx-auto", children: "Thank you for your order. Your receipt #ORD-9482 has been sent to sophia.m@gmail.com." }), _jsxs("div", { className: "p-4 rounded-2xl bg-zinc-900/60 border border-white/5 max-w-sm mx-auto text-left space-y-2", children: [_jsx("p", { className: "text-xs font-semibold text-white", children: item.name }), _jsx("p", { className: "text-[11px] text-zinc-400", children: "File size: 14.2 MB \u2022 PDF Document" })] }), _jsxs("div", { className: "pt-2 flex flex-col gap-2 max-w-sm mx-auto", children: [_jsx("a", { href: `/api/products/${item.id}/download`, className: "w-full", children: _jsxs(Button, { variant: "gradient", className: "w-full gap-2 text-xs", children: [_jsx(Download, { className: "h-4 w-4" }), "Download PDF File"] }) }), _jsx(Link, { href: "/public/rajnish", children: _jsx(Button, { variant: "ghost", className: "w-full text-xs text-zinc-400", children: "Return to Store" }) })] })] })) })] })] }));
}
