export const countries = [
    { code: "IN", name: "India", dial_code: "+91", flag: "🇮🇳", format: "##### #####" },
    { code: "US", name: "United States", dial_code: "+1", flag: "🇺🇸", format: "(###) ###-####" },
    { code: "GB", name: "United Kingdom", dial_code: "+44", flag: "🇬🇧", format: "#### ######" },
    { code: "AE", name: "United Arab Emirates", dial_code: "+971", flag: "🇦🇪", format: "## ### ####" },
    { code: "CA", name: "Canada", dial_code: "+1", flag: "🇨🇦", format: "(###) ###-####" },
    { code: "AU", name: "Australia", dial_code: "+61", flag: "🇦🇺", format: "### ### ###" },
    { code: "SG", name: "Singapore", dial_code: "+65", flag: "🇸🇬", format: "#### ####" },
    { code: "DE", name: "Germany", dial_code: "+49", flag: "🇩🇪", format: "### ########" },
    { code: "FR", name: "France", dial_code: "+33", flag: "🇫🇷", format: "# ## ## ## ##" },
    { code: "NL", name: "Netherlands", dial_code: "+31", flag: "🇳🇱", format: "# ########" },
    { code: "NZ", name: "New Zealand", dial_code: "+64", flag: "🇳🇿", format: "## ### ####" },
    { code: "ZA", name: "South Africa", dial_code: "+27", flag: "🇿🇦", format: "## ### ####" },
    { code: "BR", name: "Brazil", dial_code: "+55", flag: "🇧🇷", format: "## #####-####" },
    { code: "JP", name: "Japan", dial_code: "+81", flag: "🇯🇵", format: "## #### ####" },
    { code: "SA", name: "Saudi Arabia", dial_code: "+966", flag: "🇸🇦", format: "## ### ####" },
    { code: "MY", name: "Malaysia", dial_code: "+60", flag: "🇲🇾", format: "##-### ####" },
    { code: "ID", name: "Indonesia", dial_code: "+62", flag: "🇮🇩", format: "###-####-####" },
    { code: "NG", name: "Nigeria", dial_code: "+234", flag: "🇳🇬", format: "### ### ####" },
    { code: "PH", name: "Philippines", dial_code: "+63", flag: "🇵🇭", format: "### ### ####" },
    { code: "ES", name: "Spain", dial_code: "+34", flag: "🇪🇸", format: "### ## ## ##" },
    { code: "IT", name: "Italy", dial_code: "+39", flag: "🇮🇹", format: "### #######" },
    { code: "MX", name: "Mexico", dial_code: "+52", flag: "🇲🇽", format: "## #### ####" },
    { code: "PK", name: "Pakistan", dial_code: "+92", flag: "🇵🇰", format: "### #######" },
    { code: "BD", name: "Bangladesh", dial_code: "+880", flag: "🇧🇩", format: "####-######" },
];
