export const initialWorkspace = {
    id: "ws-rajnish-001",
    user_id: "usr-rajnish-001",
    username: "rajnish",
    display_name: "Rajnish Sharma",
    bio: "Helping creators build 6-figure digital businesses, courses & high-ticket coaching programs.",
    avatar_url: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80",
    cover_url: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=1200&auto=format&fit=crop&q=80",
    category: "Creator Business & Growth",
    instagram_handle: "rajnish_creates",
    website_url: "https://outsyra.com/rajnish",
    country: "US",
    currency: "USD",
    plan_tier: "pro",
    theme_config: {
        primaryColor: "#6366f1",
        backgroundColor: "#09090b",
        cardStyle: "glass",
        fontFamily: "Inter",
        buttonShape: "rounded-xl",
        layout: "classic",
    },
    created_at: new Date(Date.now() - 90 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
};
export const initialStoreBlocks = [
    {
        id: "block-1",
        workspace_id: "ws-rajnish-001",
        type: "header",
        title: "Rajnish Sharma",
        subtitle: "Creator & Growth Strategist 🚀",
        order_index: 0,
        is_visible: true,
    },
    {
        id: "block-2",
        workspace_id: "ws-rajnish-001",
        type: "product",
        title: "Creator Monetization Master Ebook",
        subtitle: "The complete step-by-step roadmap to $10k/mo selling digital products.",
        item_id: "prod-001",
        url: "/checkout/prod-001",
        order_index: 1,
        is_visible: true,
    },
    {
        id: "block-3",
        workspace_id: "ws-rajnish-001",
        type: "course",
        title: "Full-Stack Creator Academy (Video Course)",
        subtitle: "12 in-depth video modules + worksheets & private community access.",
        item_id: "course-001",
        url: "/checkout/course-001",
        order_index: 2,
        is_visible: true,
    },
    {
        id: "block-4",
        workspace_id: "ws-rajnish-001",
        type: "booking",
        title: "Book 1:1 30-Min Strategy Call",
        subtitle: "Private 1-on-1 session to audit your funnels & content strategy.",
        item_id: "book-001",
        url: "/book/30-min-growth-call",
        order_index: 3,
        is_visible: true,
    },
    {
        id: "block-5",
        workspace_id: "ws-rajnish-001",
        type: "coaching",
        title: "1:1 Executive Growth Mentorship",
        subtitle: "3-month hands-on partnership to scale to 6-figures.",
        item_id: "coach-001",
        url: "/coaching",
        order_index: 4,
        is_visible: true,
    },
    {
        id: "block-6",
        workspace_id: "ws-rajnish-001",
        type: "newsletter",
        title: "Join 15,000+ Creator Insiders",
        subtitle: "Weekly growth breakdowns, viral hook formulas & monetization tips.",
        order_index: 5,
        is_visible: true,
    },
    {
        id: "block-7",
        workspace_id: "ws-rajnish-001",
        type: "community",
        title: "Join Outsyra Creators Circle",
        subtitle: "Network, collaborate and share wins with high-impact creators.",
        order_index: 6,
        is_visible: true,
    },
    {
        id: "block-8",
        workspace_id: "ws-rajnish-001",
        type: "socials",
        title: "Connect with me",
        order_index: 7,
        is_visible: true,
        config: {
            instagram: "https://instagram.com/rajnish_creates",
            youtube: "https://youtube.com/@rajnish_creates",
            twitter: "https://twitter.com/rajnish_creates",
            linkedin: "https://linkedin.com/in/rajnish",
        },
    },
];
export const initialProducts = [
    {
        id: "prod-001",
        workspace_id: "ws-rajnish-001",
        name: "Creator Monetization Master Ebook",
        slug: "creator-monetization-ebook",
        description: "The definitive 120-page blueprint to scaling your creator business from $0 to $10,000/month. Covers audience building, irresistible offer design, high-converting checkout funnels, and automated email sequences.",
        price: 39.0,
        currency: "USD",
        cover_image: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=600&auto=format&fit=crop&q=80",
        category: "ebook",
        status: "published",
        file_url: "https://assets.outsyra.com/demo/creator_playbook_2026.pdf",
        file_name: "creator_monetization_master_2026.pdf",
        file_size: 14200000,
        total_sales: 184,
        seo_title: "Creator Monetization Ebook - By Rajnish Sharma",
        seo_description: "Learn how to build a scalable digital product business.",
        created_at: new Date(Date.now() - 45 * 86400000).toISOString(),
        updated_at: new Date().toISOString(),
    },
    {
        id: "prod-002",
        workspace_id: "ws-rajnish-001",
        name: "Ultimate Creator OS (Notion System)",
        slug: "notion-creator-os",
        description: "All-in-one Notion workspace for content planning, digital product inventory, client CRM, revenue tracking, and sponsorship pipelines.",
        price: 49.0,
        currency: "USD",
        cover_image: "https://images.unsplash.com/photo-1499750310107-5fef28a66643?w=600&auto=format&fit=crop&q=80",
        category: "template",
        status: "published",
        file_url: "https://assets.outsyra.com/demo/notion_creator_os_template.zip",
        file_name: "notion_creator_os_v3.zip",
        file_size: 4500000,
        total_sales: 97,
        created_at: new Date(Date.now() - 30 * 86400000).toISOString(),
        updated_at: new Date().toISOString(),
    },
    {
        id: "prod-003",
        workspace_id: "ws-rajnish-001",
        name: "Viral Short-Form Hook Vault (300+ Hooks)",
        slug: "viral-short-form-hook-vault",
        description: "Tested hook templates for Instagram Reels, TikTok, and YouTube Shorts that have generated over 50M+ collective impressions.",
        price: 19.0,
        currency: "USD",
        cover_image: "https://images.unsplash.com/photo-1611162617474-5b21e879e113?w=600&auto=format&fit=crop&q=80",
        category: "pdf",
        status: "published",
        file_url: "https://assets.outsyra.com/demo/viral_hooks_vault.pdf",
        file_name: "viral_hook_vault_2026.pdf",
        file_size: 8200000,
        total_sales: 242,
        created_at: new Date(Date.now() - 60 * 86400000).toISOString(),
        updated_at: new Date().toISOString(),
    },
];
export const initialCourses = [
    {
        id: "course-001",
        workspace_id: "ws-rajnish-001",
        title: "Full-Stack Creator Academy: Zero to 6-Figures",
        slug: "full-stack-creator-academy",
        subtitle: "Complete video masterclass covering content, digital products, high-ticket offers and automation.",
        description: "An intensive, practical LMS course designed to turn your knowledge into an automated revenue generating engine. Learn high-retention video creation, launch strategies, checkout conversions, and community scaling.",
        thumbnail_url: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800&auto=format&fit=crop&q=80",
        price: 199.0,
        is_free: false,
        currency: "USD",
        status: "published",
        total_students: 86,
        certificate_enabled: true,
        modules: [
            {
                id: "mod-1",
                course_id: "course-001",
                title: "Module 1: Positioning & Niche Domination",
                order_index: 0,
                lessons: [
                    {
                        id: "les-101",
                        module_id: "mod-1",
                        course_id: "course-001",
                        title: "1.1 Finding Your High-Value Creator Niche",
                        type: "video",
                        video_url: "https://www.w3schools.com/html/mov_bbb.mp4",
                        duration_minutes: 18,
                        order_index: 0,
                        is_free_preview: true,
                        content: "In this lesson, we break down the 3-pillar framework for picking a creator niche with high willingness-to-pay.",
                    },
                    {
                        id: "les-102",
                        module_id: "mod-1",
                        course_id: "course-001",
                        title: "1.2 Audience Avatar & Problem Statement Matrix",
                        type: "text",
                        duration_minutes: 12,
                        order_index: 1,
                        is_free_preview: false,
                        content: "Define your ideal customer profile with surgical precision using this worksheet.",
                    },
                ],
            },
            {
                id: "mod-2",
                course_id: "course-001",
                title: "Module 2: Product Architecture & Pricing",
                order_index: 1,
                lessons: [
                    {
                        id: "les-201",
                        module_id: "mod-2",
                        course_id: "course-001",
                        title: "2.1 Crafting Your First $100+ Digital Offer",
                        type: "video",
                        video_url: "https://www.w3schools.com/html/mov_bbb.mp4",
                        duration_minutes: 24,
                        order_index: 0,
                        is_free_preview: false,
                        content: "Learn the offer packaging framework that turns browsers into buyers.",
                    },
                    {
                        id: "les-202",
                        module_id: "mod-2",
                        course_id: "course-001",
                        title: "2.2 Module Quiz: Offer Validation",
                        type: "quiz",
                        duration_minutes: 10,
                        order_index: 1,
                        is_free_preview: false,
                        quiz_data: {
                            questions: [
                                {
                                    id: "q1",
                                    question: "What is the single most important element of an irresistible digital product?",
                                    options: [
                                        "A 500-page lengthy document",
                                        "A specific, high-urgency outcome for a clear target buyer",
                                        "A low $5 price point",
                                        "Complex custom software",
                                    ],
                                    correct_answer_index: 1,
                                },
                                {
                                    id: "q2",
                                    question: "How do you calculate product-market fit for digital products?",
                                    options: [
                                        "Number of likes on Twitter",
                                        "Consistent conversion rate > 3% from qualified organic traffic",
                                        "Number of free downloads",
                                        "Having a cool logo",
                                    ],
                                    correct_answer_index: 1,
                                },
                            ],
                        },
                    },
                ],
            },
        ],
        created_at: new Date(Date.now() - 30 * 86400000).toISOString(),
        updated_at: new Date().toISOString(),
    },
];
export const initialBookingServices = [
    {
        id: "book-001",
        workspace_id: "ws-rajnish-001",
        title: "30-Minute Growth Strategy Call",
        slug: "30-min-growth-call",
        description: "Deep dive 1:1 strategy session to audit your bio, funnel conversion, and digital product roadmap. Includes recording + action checklist.",
        duration_minutes: 30,
        price: 99.0,
        currency: "USD",
        buffer_before_minutes: 5,
        buffer_after_minutes: 10,
        max_bookings_per_day: 4,
        location_type: "jitsi",
        is_active: true,
        cancellation_policy: "Free cancellation or reschedule up to 24 hours prior to meeting time.",
        questions: [
            { id: "q1", label: "What is your main creator handle/website?", required: true, type: "text" },
            { id: "q2", label: "What is your #1 bottleneck right now?", required: true, type: "textarea" },
        ],
    },
    {
        id: "book-002",
        workspace_id: "ws-rajnish-001",
        title: "60-Minute Intensive Offer & Launch Audit",
        slug: "60-min-launch-audit",
        description: "Comprehensive review of your upcoming course or product launch, pricing psychology, email sequence copy, and ad creatives.",
        duration_minutes: 60,
        price: 180.0,
        currency: "USD",
        buffer_before_minutes: 10,
        buffer_after_minutes: 15,
        max_bookings_per_day: 2,
        location_type: "jitsi",
        is_active: true,
        cancellation_policy: "Free reschedule up to 24 hours in advance.",
    },
];
export const initialCoachingOffers = [
    {
        id: "coach-001",
        workspace_id: "ws-rajnish-001",
        title: "1:1 Executive Growth Mentorship (90 Days)",
        description: "High-touch 1-on-1 partnership to scale your creator business to predictable $10k+ monthly recurring income.",
        price: 1200.0,
        currency: "USD",
        duration_minutes: 60,
        frequency: "monthly",
        includes: [
            "Bi-weekly 60-minute 1:1 video strategy sessions",
            "Direct WhatsApp / Slack access for asynchronous feedback",
            "Full funnel, copywriting & landing page review",
            "Automated email sequence and Instagram workflow setup",
        ],
        intake_questions: [
            "What is your current monthly revenue?",
            "What is your revenue goal for the next 90 days?",
            "How many followers/subscribers do you currently have?",
        ],
        is_active: true,
        created_at: new Date(Date.now() - 40 * 86400000).toISOString(),
    },
];
export const initialInstagramRules = [
    {
        id: "rule-001",
        workspace_id: "ws-rajnish-001",
        name: "Auto-DM: Ebook Keyword Trigger",
        trigger_type: "comment_keyword",
        trigger_keywords: ["EBOOK", "PLAYBOOK", "GUIDE", "START"],
        response_type: "send_dm",
        response_message: "Hey! 🎉 Here is your direct access link to the Creator Monetization Master Ebook: https://outsyra.com/rajnish/product/creator-monetization-ebook. Let me know if you have any questions!",
        is_active: true,
        executions_count: 248,
        created_at: new Date(Date.now() - 20 * 86400000).toISOString(),
    },
    {
        id: "rule-002",
        workspace_id: "ws-rajnish-001",
        name: "Auto-DM: Course Access Keyword Trigger",
        trigger_type: "comment_keyword",
        trigger_keywords: ["COURSE", "ACADEMY", "LEARN"],
        response_type: "send_dm",
        response_message: "Awesome to hear! 🚀 Here is the exclusive link to Full-Stack Creator Academy: https://outsyra.com/rajnish/course/full-stack-creator-academy",
        is_active: true,
        executions_count: 115,
        created_at: new Date(Date.now() - 15 * 86400000).toISOString(),
    },
];
export const initialEmailSubscribers = [
    {
        id: "sub-01",
        workspace_id: "ws-rajnish-001",
        email: "alex.taylor@gmail.com",
        name: "Alex Taylor",
        tags: ["vip", "ebook_buyer"],
        status: "subscribed",
        source: "link_in_bio",
        created_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    },
    {
        id: "sub-02",
        workspace_id: "ws-rajnish-001",
        email: "sarah.miller@outlook.com",
        name: "Sarah Miller",
        tags: ["newsletter", "webinar"],
        status: "subscribed",
        source: "instagram_automation",
        created_at: new Date(Date.now() - 5 * 86400000).toISOString(),
    },
    {
        id: "sub-03",
        workspace_id: "ws-rajnish-001",
        email: "david.chen@techstartup.io",
        name: "David Chen",
        tags: ["course_student"],
        status: "subscribed",
        source: "checkout",
        created_at: new Date(Date.now() - 10 * 86400000).toISOString(),
    },
];
export const initialEmailCampaigns = [
    {
        id: "camp-001",
        workspace_id: "ws-rajnish-001",
        subject: "The 3-step funnel that made $14,000 this month 🚀",
        preview_text: "Here is the exact breakdown with screenshots and templates...",
        content: "Hey creator,\n\nLast week I audited over 20 creator link-in-bios. 90% of them made the exact same fatal mistake: sending traffic to 15 different links without a clear primary call-to-action.\n\nHere is how we fixed it...",
        target_tags: ["newsletter", "ebook_buyer"],
        status: "sent",
        sent_at: new Date(Date.now() - 3 * 86400000).toISOString(),
        total_recipients: 1240,
        open_rate: 46.8,
        click_rate: 14.2,
        created_at: new Date(Date.now() - 4 * 86400000).toISOString(),
    },
];
export const initialTemplates = [
    {
        id: "tmpl-01",
        title: "Viral Tech & AI Carousel Slide",
        category: "instagram_post",
        thumbnail_url: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=500&auto=format&fit=crop&q=80",
        tags: ["Carousel", "Tech", "Viral", "Modern"],
        is_featured: true,
        canvas_json: {
            width: 1080,
            height: 1080,
            background: "#09090b",
            elements: [
                { id: "el-1", type: "badge", content: "GROWTH SECRETS 💡", x: 60, y: 80, width: 220, height: 40, color: "#6366f1", borderRadius: 8 },
                { id: "el-2", type: "text", content: "How to Build a $10k/mo\nDigital Store in 2026", x: 60, y: 160, width: 960, height: 200, color: "#ffffff", fontSize: 56, fontWeight: "bold" },
                { id: "el-3", type: "text", content: "Stop wasting time on 10 fragmented tools. Here is the streamlined 1-link stack that converts 3x higher.", x: 60, y: 400, width: 960, height: 160, color: "#94a3b8", fontSize: 32 },
            ],
        },
    },
    {
        id: "tmpl-02",
        title: "Minimalist YouTube Thumbnail Layout",
        category: "youtube_thumbnail",
        thumbnail_url: "https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=500&auto=format&fit=crop&q=80",
        tags: ["YouTube", "High-CTR", "Dark"],
        is_featured: true,
        canvas_json: {
            width: 1280,
            height: 720,
            background: "#030712",
            elements: [
                { id: "el-1", type: "badge", content: "CASE STUDY", x: 80, y: 80, width: 200, height: 50, color: "#22c55e", borderRadius: 12 },
                { id: "el-2", type: "text", content: "0 TO $100K IN 90 DAYS", x: 80, y: 160, width: 1120, height: 180, color: "#f8fafc", fontSize: 64, fontWeight: "900" },
                { id: "el-3", type: "text", content: "Step-by-step breakdown (No Gatekeeping)", x: 80, y: 380, width: 1120, height: 100, color: "#38bdf8", fontSize: 36 },
            ],
        },
    },
    {
        id: "tmpl-03",
        title: "Gradient Reels / TikTok Cover",
        category: "reels_cover",
        thumbnail_url: "https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?w=500&auto=format&fit=crop&q=80",
        tags: ["Reels", "Gradient", "Trendy"],
        is_featured: false,
        canvas_json: {
            width: 1080,
            height: 1920,
            background: "linear-gradient(135deg, #4f46e5 0%, #7c3aed 50%, #db2777 100%)",
            elements: [
                { id: "el-1", type: "text", content: "5 TOOLS YOU NEED AS A CREATOR", x: 80, y: 600, width: 920, height: 300, color: "#ffffff", fontSize: 64, fontWeight: "800" },
            ],
        },
    },
];
export const initialCommunities = [
    { id: "chan-1", community_id: "comm-01", name: "announcements", description: "Official updates, drops and news", is_private: false },
    { id: "chan-2", community_id: "comm-01", name: "general-chat", description: "Hangout and discuss creator strategies", is_private: false },
    { id: "chan-3", community_id: "comm-01", name: "wins-and-milestones", description: "Celebrate your product sales and breakthroughs", is_private: false },
    { id: "chan-4", community_id: "comm-01", name: "feedback-and-reviews", description: "Get peer feedback on your store & offers", is_private: false },
];
export const initialCommunityPosts = [
    {
        id: "post-1",
        workspace_id: "ws-rajnish-001",
        channel_id: "chan-3",
        author_id: "usr-01",
        author_name: "Elena Rostova",
        author_avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80",
        title: "Crossed $3,500 in my second week! 🎉",
        content: "Huge shoutout to the community! Switched to Outsyra for my link-in-bio and digital templates store. The conversion rate on mobile is insane compared to my old setup.",
        likes_count: 42,
        comments_count: 9,
        is_pinned: true,
        created_at: new Date(Date.now() - 1 * 86400000).toISOString(),
    },
    {
        id: "post-2",
        workspace_id: "ws-rajnish-001",
        channel_id: "chan-2",
        author_id: "usr-02",
        author_name: "Marcus Sterling",
        author_avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
        title: "Instagram Comment Automations are a game changer",
        content: "Hooked up the 'Comment EBOOK' keyword rule yesterday and woke up to 18 new automated sales in Stripe without opening the app once. Incredible flow.",
        likes_count: 28,
        comments_count: 6,
        is_pinned: false,
        created_at: new Date(Date.now() - 3 * 86400000).toISOString(),
    },
];
export const initialOrders = [
    {
        id: "ord-101",
        workspace_id: "ws-rajnish-001",
        customer_name: "Sophia Martinez",
        customer_email: "sophia.m@gmail.com",
        item_type: "course",
        item_id: "course-001",
        item_name: "Full-Stack Creator Academy",
        amount: 199.0,
        currency: "USD",
        payment_provider: "stripe",
        payment_id: "pi_3N928...live",
        status: "completed",
        created_at: new Date(Date.now() - 1 * 3600000).toISOString(),
    },
    {
        id: "ord-102",
        workspace_id: "ws-rajnish-001",
        customer_name: "Liam O'Connor",
        customer_email: "liam.oc@outlook.com",
        item_type: "booking",
        item_id: "book-001",
        item_name: "30-Minute Growth Strategy Call",
        amount: 99.0,
        currency: "USD",
        payment_provider: "stripe",
        payment_id: "pi_3N929...live",
        status: "completed",
        created_at: new Date(Date.now() - 4 * 3600000).toISOString(),
    },
    {
        id: "ord-103",
        workspace_id: "ws-rajnish-001",
        customer_name: "Emma Watson",
        customer_email: "emma.w@designlab.co",
        item_type: "product",
        item_id: "prod-001",
        item_name: "Creator Monetization Master Ebook",
        amount: 39.0,
        currency: "USD",
        payment_provider: "razorpay",
        payment_id: "pay_N8329...live",
        status: "completed",
        created_at: new Date(Date.now() - 8 * 3600000).toISOString(),
    },
    {
        id: "ord-104",
        workspace_id: "ws-rajnish-001",
        customer_name: "Noah Becker",
        customer_email: "noah.becker@creator.de",
        item_type: "product",
        item_id: "prod-002",
        item_name: "Ultimate Creator OS (Notion System)",
        amount: 49.0,
        currency: "USD",
        payment_provider: "stripe",
        payment_id: "pi_3N930...live",
        status: "completed",
        created_at: new Date(Date.now() - 14 * 3600000).toISOString(),
    },
];
