"use client";
import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import React, { useState } from "react";
import Link from "next/link";
import { Video, CheckCircle2, ArrowLeft, } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import { Card } from "@/components/ui/card";
import { initialBookingServices } from "@/lib/supabase/mock-db";
export default function StandaloneBookPage({ params, }) {
    const [selectedSlot, setSelectedSlot] = useState("11:00 AM");
    const [completed, setCompleted] = useState(false);
    const service = initialBookingServices[0];
    return (_jsxs("div", { className: "min-h-screen bg-zinc-950 text-zinc-100 flex flex-col justify-center py-12 px-4 sm:px-6 lg:px-8 grid-bg relative overflow-hidden", children: [_jsx("div", { className: "absolute top-1/3 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[600px] h-[350px] bg-indigo-500/15 blur-[140px] rounded-full pointer-events-none" }), _jsxs("div", { className: "max-w-xl mx-auto w-full relative z-10 space-y-6", children: [_jsxs(Link, { href: "/public/rajnish", className: "inline-flex items-center gap-2 text-xs text-zinc-400 hover:text-white transition-colors", children: [_jsx(ArrowLeft, { className: "h-4 w-4" }), "Back to Store"] }), _jsx(Card, { className: "glass-panel border-white/10 p-6 md:p-8 rounded-3xl shadow-2xl space-y-6", children: !completed ? (_jsxs(_Fragment, { children: [_jsxs("div", { className: "flex items-center justify-between border-b border-white/5 pb-4", children: [_jsxs(Badge, { variant: "gradient", className: "text-xs", children: [service.duration_minutes, " Minutes"] }), _jsxs("span", { className: "text-sm font-bold text-emerald-400", children: ["$", service.price.toFixed(2), " USD"] })] }), _jsxs("div", { children: [_jsx("h1", { className: "text-xl font-extrabold text-white", children: service.title }), _jsx("p", { className: "text-xs text-zinc-400 mt-1 leading-relaxed", children: service.description })] }), _jsxs("div", { className: "space-y-3", children: [_jsx("label", { className: "block text-xs font-semibold text-zinc-300", children: "Select Date & Time Slot" }), _jsx("div", { className: "grid grid-cols-3 gap-2", children: ["09:30 AM", "11:00 AM", "03:00 PM"].map((slot) => (_jsx("button", { type: "button", onClick: () => setSelectedSlot(slot), className: `p-3 rounded-2xl text-xs font-mono border transition-all ${selectedSlot === slot
                                                    ? "bg-indigo-600 border-indigo-500 text-white font-bold"
                                                    : "bg-zinc-900/60 border-white/5 text-zinc-300 hover:bg-zinc-900"}`, children: slot }, slot))) })] }), _jsxs("div", { className: "space-y-3", children: [_jsxs("div", { children: [_jsx("label", { className: "block text-xs font-medium text-zinc-300 mb-1", children: "Your Full Name" }), _jsx(Input, { defaultValue: "Liam O'Connor", className: "text-xs" })] }), _jsxs("div", { children: [_jsx("label", { className: "block text-xs font-medium text-zinc-300 mb-1", children: "Email Address (for calendar invite)" }), _jsx(Input, { type: "email", defaultValue: "liam.oc@outlook.com", className: "text-xs" })] })] }), _jsxs(Button, { variant: "gradient", className: "w-full h-12 text-sm font-bold shadow-lg", onClick: () => setCompleted(true), children: ["Confirm Appointment ($", service.price.toFixed(2), ")"] })] })) : (_jsxs("div", { className: "text-center py-8 space-y-4", children: [_jsx("div", { className: "h-14 w-14 rounded-full bg-emerald-500/20 text-emerald-400 flex items-center justify-center mx-auto", children: _jsx(CheckCircle2, { className: "h-8 w-8" }) }), _jsx("h2", { className: "text-2xl font-extrabold text-white", children: "Booking Confirmed! \uD83D\uDCC5" }), _jsxs("p", { className: "text-xs text-zinc-300 max-w-sm mx-auto", children: ["Your session is booked for ", _jsxs("strong", { className: "text-white", children: ["Tomorrow at ", selectedSlot] }), ". A Google Meet & Jitsi room invite has been added to your calendar."] }), _jsxs("div", { className: "pt-2 flex flex-col gap-2 max-w-sm mx-auto", children: [_jsx("a", { href: "https://meet.jit.si/outsyra-call-liam-38492", target: "_blank", className: "w-full", children: _jsxs(Button, { variant: "gradient", className: "w-full gap-2 text-xs", children: [_jsx(Video, { className: "h-4 w-4" }), "Open Video Meeting Room"] }) }), _jsx(Link, { href: "/public/rajnish", children: _jsx(Button, { variant: "ghost", className: "w-full text-xs text-zinc-400", children: "Return to Store" }) })] })] })) })] })] }));
}
